### ISSUE TITLE
문자열 인코딩 개념

### ISSUE THREAD

**Issue by kongukjae** [jueun11/javascript-algorithm#1]
ASCII : 아스키코드로 '영어'만 지원하는 문자표이며, 문자 마다 번호가 할당 되어있다.
특징은 문자 하나당 1byte = 8bit 데이터를 차지하며 유니코드(UTF-8) 2byte 를 차지한다.

UTF-8 : 전세계의 언어를 포괄하려고 제작하였기에 한글의 경우 문자(char)당 2byte가 필요하다.

**Comment by jueun11** [comment]
오타수정완료했습니다.
